### ISSUE TITLE
Error during 'make'

### ISSUE THREAD

**Issue by teis-e** [ip2location/IP2Location-Varnish#7]
make  all-recursive
make[1]: Entering directory '/root/IP2Location-Varnish'
Making all in src
make[2]: Entering directory '/root/IP2Location-Varnish/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish  -Wall -Wextra -Werror -g -O2 -MT vmod_ip2location.lo -MD -MP -MF .deps/vmod_ip2location.Tpo -c -o vmod_ip2location.lo vmod_ip2location.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -Werror -g -O2 -MT vmod_ip2location.lo -MD -MP -MF .deps/vmod_ip2location.Tpo -c vmod_ip2location.c  -fPIC -DPIC -o .libs/vmod_ip2location.o
vmod_ip2location.c:23:39: error: array type has incomplete element type ‘struct vmod_priv_methods’
   23 | static const struct vmod_priv_methods ip2l_methods[1] = {{
      |                                       ^~~~~~~~~~~~
vmod_ip2location.c:24:2: error: field name not in record or union initializer
   24 |  .magic = VMOD_PRIV_METHODS_MAGIC,
      |  ^
vmod_ip2location.c:24:2: note: (near initialization for ‘ip2l_methods’)
vmod_ip2location.c:24:11: error: ‘VMOD_PRIV_METHODS_MAGIC’ undeclared here (not in a function); did you mean ‘VDI_METHODS_MAGIC’?
   24 |  .magic = VMOD_PRIV_METHODS_MAGIC,
      |           ^~~~~~~~~~~~~~~~~~~~~~~
      |           VDI_METHODS_MAGIC
vmod_ip2location.c:25:2: error: field name not in record or union initializer
   25 |  .type = "vmod_std_ip2location",
      |  ^
vmod_ip2location.c:25:2: note: (near initialization for ‘ip2l_methods’)
vmod_ip2location.c:26:2: error: field name not in record or union initializer
   26 |  .fini = ip2l_free
      |  ^
vmod_ip2location.c:26:2: note: (near initialization for ‘ip2l_methods’)
vmod_ip2location.c: In function ‘vmod_init_db’:
vmod_ip2location.c:61:6: error: ‘struct vmod_priv’ has no member named ‘methods’
   61 |  priv->methods = ip2l_methods;
      |      ^~
vmod_ip2location.c: In function ‘convert’:
vmod_ip2location.c:79:2: error: ignoring return value of ‘gcvt’, declared with attribute warn_unused_result [-Werror=unused-result]
   79 |  gcvt(f, 5, buf);
      |  ^~~~~~~~~~~~~~~
At top level:
vmod_ip2location.c:23:39: error: ‘ip2l_methods’ defined but not used [-Werror=unused-variable]
   23 | static const struct vmod_priv_methods ip2l_methods[1] = {{
      |                                       ^~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:455: vmod_ip2location.lo] Error 1
make[2]: Leaving directory '/root/IP2Location-Varnish/src'
make[1]: *** [Makefile:514: all-recursive] Error 1
make[1]: Leaving directory '/root/IP2Location-Varnish'
make: *** [Makefile:382: all] Error 2

**Comment by teis-e** [comment]
Varnish version:

![Scherm­afbeelding 2023-04-05 om 01 04 59](https://user-images.githubusercontent.com/89307927/229941284-1025e111-742b-41ef-8444-1394f6e8cc41.png)

**Comment by ip2location** [comment]
Hi teis-e,

We have tried on our machine, and we found out that the issue may occurred because of missing **varnish-dev** package. If you didn't install this package yet, can you please try install it first before try again?

**Comment by jgarrouste** [comment]
@ip2location It seem that the method VMOD_PRIV_METHODS_MAGIC has been introduced in Varnish 6.6.0 (https://github.com/varnishcache/varnish-cache/commit/681c11998ec56dc4460a30585210f95a7850ea3b)


The build failed using Varnish 6.5.2.
I used the Varnish Ubuntu (focal) package from https://packagecloud.io/varnishcache/varnish65/

```
# dpkg -l | grep varnish
ii  varnish                      6.5.2~focal-1                           amd64        state of the art, high-performance web accelerator
ii  varnish-dev                  6.5.2~focal-1                           amd64        development files for Varnish Cache
```

```
# git clone https://github.com/ip2location/IP2Location-Varnish.git
# cd IP2Location-Varnish/
# ./autogen.sh && ./configure && make
make  all-recursive
make[1]: Entering directory '/root/IP2Location-Varnish'
Making all in src
make[2]: Entering directory '/root/IP2Location-Varnish/src'
/usr/share/varnish/vmodtool.py ../src/vmod_ip2location.vcc
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish  -Wall -Wextra -Werror -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c -o vcc_if.lo vcc_if.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -Werror -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c  -fPIC -DPIC -o .libs/vcc_if.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -Werror -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c -o vcc_if.o >/dev/null 2>&1
mv -f .deps/vcc_if.Tpo .deps/vcc_if.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish  -Wall -Wextra -Werror -g -O2 -MT vmod_ip2location.lo -MD -MP -MF .deps/vmod_ip2location.Tpo -c -o vmod_ip2location.lo vmod_ip2location.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -Werror -g -O2 -MT vmod_ip2location.lo -MD -MP -MF .deps/vmod_ip2location.Tpo -c vmod_ip2location.c  -fPIC -DPIC -o .libs/vmod_ip2location.o
vmod_ip2location.c:23:39: error: array type has incomplete element type 'struct vmod_priv_methods'
   23 | static const struct vmod_priv_methods ip2l_methods[1] = {{
      |                                       ^~~~~~~~~~~~
vmod_ip2location.c:24:18: error: 'VMOD_PRIV_METHODS_MAGIC' undeclared here (not in a function); did you mean 'VDI_METHODS_MAGIC'?
   24 |         .magic = VMOD_PRIV_METHODS_MAGIC,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
      |                  VDI_METHODS_MAGIC
vmod_ip2location.c: In function 'vmod_init_db':
vmod_ip2location.c:61:13: error: 'struct vmod_priv' has no member named 'methods'
   61 |         priv->methods = ip2l_methods;
      |             ^~
vmod_ip2location.c: In function 'convert':
vmod_ip2location.c:79:9: error: ignoring return value of 'gcvt' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   79 |         gcvt(f, 5, buf);
      |         ^~~~~~~~~~~~~~~
At top level:
vmod_ip2location.c:23:39: error: 'ip2l_methods' defined but not used [-Werror=unused-variable]
   23 | static const struct vmod_priv_methods ip2l_methods[1] = {{
      |                                       ^~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:456: vmod_ip2location.lo] Error 1
make[2]: Leaving directory '/root/IP2Location-Varnish/src'
make[1]: *** [Makefile:516: all-recursive] Error 1
make[1]: Leaving directory '/root/IP2Location-Varnish'
make: *** [Makefile:384: all] Error 2
```

**Comment by ip2location** [comment]
Hi @teis-e,

We haven’t heard back from you in a while, and the issue seems to have stalled. Therefore, we’re going to close this issue for now.

If you are still experiencing this problem or have more details to provide, please feel free to reopen the issue or create a new one with the updated information.
